<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);">Sau một thời gian d&agrave;i thưc hiện việc đội mũ bảo hiểm dần trở th&agrave;nh một th&oacute;i quen mỗi khi ra đường tham gia giao th&ocirc;ng. V&agrave; người d&acirc;n cũng dần nhận thức được lợi &iacute;ch thiết thực khi sử dụng mũ bảo hiểm. Nhưng tr&ecirc;n thị trường c&oacute; qu&aacute; nhiều sản phẩm k&eacute;m chất lượng kh&ocirc;ng c&oacute; khả năng bảo vệ sự an to&agrave;n của bạn. Sản phẩm Mũ bảo hiểm c&oacute; k&iacute;nhch&iacute;nh h&atilde;ng Minh Ho&agrave;ng d&agrave;nh cho người lớn, &nbsp;kh&ocirc;ng chỉ gi&uacute;p bảo vệ an to&agrave;n cho bạn v&agrave; người th&acirc;n m&agrave; c&ograve;n mang đến phong c&aacute;ch mới mẻ, trẻ trung cho bạn.</span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0823/13772303391153.jpg" src="http://www.dealvip.vn/static/team/2013/0823/13772303391153.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0829/13777471536294.jpg" src="http://www.dealvip.vn/static/team/2013/0829/13777471536294.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0829/13777471665081.jpg" src="http://www.dealvip.vn/static/team/2013/0829/13777471665081.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><strong style="margin: 0px; padding: 0px; outline: 0px;">TH&Ocirc;NG TIN CHI TIẾT SẢN PHẨM:</strong></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);">T&ecirc;n sản phẩm: &nbsp;N&oacute;n Bảo Hiểm C&oacute; K&iacute;nh Ch&iacute;nh H&atilde;ng Miền T&acirc;y Mua.</span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);">M&agrave;u sắc: Trắng, xanh dương, v&agrave;ng, đỏ, đen.</span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);">Chất liệu:&nbsp;<span style="margin: 0px; padding: 0px; outline: 0px;">Xuất từ nhựa ABS nhập khẩu chuy&ecirc;n dụng cho sản phẩm mũ bảo hiểm, c&oacute; t&iacute;nh năng chịu lực va đập cao.</span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><span style="margin: 0px; padding: 0px; outline: 0px;">K&iacute;ch cỡ : Free size.</span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><span style="margin: 0px; padding: 0px; outline: 0px;">Cấu tạo gọn nhẹ tạo cảm gi&aacute;c thoải m&aacute;i, th&ocirc;ng tho&aacute;ng, ph&ugrave; hợp với kh&iacute; hậu nhiệt đới v&agrave; mật độ giao th&ocirc;ng d&agrave;y đặc của Việt Nam.</span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);">Xuất xứ: Việt Nam.</span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0823/13772304609443.jpg" src="http://www.dealvip.vn/static/team/2013/0823/13772304609443.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0823/13772304669830.jpg" src="http://www.dealvip.vn/static/team/2013/0823/13772304669830.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p dir="ltr" style="margin: 0pt 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; vertical-align: baseline;">Mũ c&oacute; k&iacute;nh chắn gi&oacute; bằng nhựa trong suốt, gi&uacute;p bảo vệ đ&ocirc;i mắt khi đi đường.&nbsp;</span>Lớp đệm xốp b&ecirc;n trong d&agrave;y, c&oacute; bề mặt đanh chắc, hấp thụ xung động tốt.</p>
<p>
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0823/13772304749143.jpg" src="http://www.dealvip.vn/static/team/2013/0823/13772304749143.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0823/13772304782853.jpg" src="http://www.dealvip.vn/static/team/2013/0823/13772304782853.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0903/13781937427703.jpg" src="http://www.dealvip.vn/static/team/2013/0903/13781937427703.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0903/13781937487738.jpg" src="http://www.dealvip.vn/static/team/2013/0903/13781937487738.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p dir="ltr" style="margin: 0pt 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><span style="margin: 0px; padding: 0px; outline: 0px; vertical-align: baseline;">D&acirc;y quai n&oacute;n c&oacute; độ chịu lực cao.&nbsp;</span>Bộ kho&aacute; n&oacute;n an to&agrave;n, dễ g&agrave;i, dễ mở nhưng kh&ocirc;ng bị tuột.</span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0823/13772304826589.jpg" src="http://www.dealvip.vn/static/team/2013/0823/13772304826589.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0823/13772304878535.jpg" src="http://www.dealvip.vn/static/team/2013/0823/13772304878535.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><span style="margin: 0px; padding: 0px; outline: 0px;">Cấu tạo gọn nhẹ tạo cảm gi&aacute;c thoải m&aacute;i, th&ocirc;ng tho&aacute;ng, ph&ugrave; hợp với kh&iacute; hậu nhiệt đới v&agrave; mật độ giao th&ocirc;ng d&agrave;y đặc của Việt Nam.</span></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0823/13772304926191.jpg" src="http://www.dealvip.vn/static/team/2013/0823/13772304926191.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0823/13772304973242.jpg" src="http://www.dealvip.vn/static/team/2013/0823/13772304973242.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;">D&ugrave;ng cho người đi m&ocirc;t&ocirc;, xe m&aacute;y.</span></span></p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	&nbsp;</p>
<p style="margin: 0px; padding: 0px; outline: 0px; color: rgb(88, 88, 88); line-height: 21px; font-family: Arial, Helvetica, sans-serif; font-size: 14px;">
	<span style="margin: 0px; padding: 0px; outline: 0px; text-align: justify;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px;"><span style="margin: 0px; padding: 0px; outline: 0px; font-family: 'Times New Roman'; font-size: medium; color: rgb(51, 51, 51);"><img alt="" original="http://www.dealvip.vn/static/team/2013/0823/13772305032650.jpg" src="http://www.dealvip.vn/static/team/2013/0823/13772305032650.jpg" style="margin: 0px; padding: 0px; outline: 0px; border: 1px solid rgb(153, 153, 153); display: block; width: 660px;" /></span></span></span></span></span></p>
<div>
	&nbsp;</div>
