<?php $_config_vars = array (
  'sections' => 
  array (
  ),
  'vars' => 
  array (
    'default_title' => 'Dong Luc Group',
    'default_description' => 'Dong Luc Group',
    'default_keyword' => 'Dong Luc Group',
    'product_title' => 'Sản phẩm',
    'product_description' => 'Sản phẩm',
    'product_keyword' => 'Sản phẩm',
    'contact_title' => 'Liên hệ',
    'contact_description' => 'Liên hệ',
    'contact_keyword' => 'Liên hệ',
    'news_title' => 'Thông tin',
    'news_description' => 'Thông tin',
    'news_keyword' => 'Thông tin',
    'copyright' => '',
    'company_contact' => '',
    'phone_contact_mienbac' => '',
    'phone_contact_miennam' => '',
    'email_contact' => '',
    'address_contact' => '',
    'hotnews' => 'Tin mới nhất',
    'text_menu_home' => 'Trang chủ',
    'text_menu_about' => 'Giới thiệu',
    'text_menu_contact' => 'Liên hệ',
    'text_menu_news' => 'Thông tin',
    'text_menu_product' => 'Sản phẩm',
    'text_menu_faq' => 'Hỏi đáp',
    '404_title' => 'Không tìm thấy trang web bạn yêu cầu',
    '404_content' => 'Xin lỗi, nội dung bạn đang tìm kiếm hiện tại không tìm thấy. Hãy quay về trang chủ hoặc các chuyên mục khác để tìm thấy nội dung của mình, hoặc bạn có thể liên hệ với chúng tôi để được trợ giúp!',
    '404_title_suggest' => 'Có thể bạn quan tâm',
    '404_title_thank' => 'Trân trọng!!!',
    'form_contact_name' => 'Họ tên',
    'form_contact_phone' => 'Số điện thoại',
    'form_contact_address' => 'Địa chỉ',
    'form_contact_email' => 'Địa chỉ email',
    'form_contact_message' => 'Nội dung',
    'form_contact_error' => 'Đã có lỗi xảy ra:',
    'form_contact_name_require' => 'Họ tên là bắt buộc',
    'form_contact_phone_require' => 'Số điện thoại là bắt buộc',
    'form_contact_address_require' => 'Địa chỉ là bắt buộc',
    'form_contact_email_require' => 'Email là bắt buộc',
    'form_contact_message_require' => 'Nội dung là bắt buộc',
    'form_contact_success' => 'Gửi liên hệ thành công!',
    'search_title' => 'Kết quả tìm kiếm',
    'search_error' => 'Không có sản phẩm nào',
    'search_alert_error' => 'Vui lòng nhập từ khóa để tìm kiếm!',
  ),
); ?>